import './utils.js'
import './constants.js'
import './animation.js'
import './script.js'
import './pause.js'
import './progress-line.js'
import './block.js'
import './board.js'
import './frame.js'
import './score.js'
import './text.js'
import './game.js'

